arike/facility/urls.py
from django.urls import include, path
from arike.facility.models.patients import TreatmentNotes
from arike.facility.view import CreateFacility, UpdateFacility, DetailFacility, ViewFacility, DeleteFacility
from arike.facility.views.patients import CreatePatient, UpdatePatient, ViewPatient, DetailPatient, DeletePatient, load_facilities
from arike.facility.views.family import CreateFamily, UpdateFamily, ViewFamily, DetailFamily, DeleteFamily
from arike.facility.views.disease import CreateDisease, UpdateDisease, ViewDisease, DetailDisease, DeleteDisease
from arike.facility.views.treatment import CreateTreatment, DeleteTreatment, DetailTreatment, UpdateTreatment, ViewTreatment
from arike.facility.views.home import HomeView
from arike.facility.views.visit import AddTreatmentNotes, Agenda, CreateVisit, DeleteVisit, DetailHistory, DetailVisit, PatientInfo, ViewHistoy, ViewTreatmentNotes, ViewVisit, VisitPatient
from arike.facility.viewset import FacilityViewSet
from rest_framework_nested import routers

router = routers.SimpleRouter()
router.register("api/facility", FacilityViewSet)

patient_patterns = [
  path("family/create/", CreateFamily.as_view(), name="add-family"),
  path("family/update/<int:pk>/", UpdateFamily.as_view(), name="update-family"),
  path("family/detail/<int:pk>/", DetailFamily.as_view(), name="detail-family"),
  path("family/view/", ViewFamily.as_view(), name="view-family"),
  path("family/delete/<int:pk>/", DeleteFamily.as_view(), name="delete-family"),
  path("disease/create/", CreateDisease.as_view(), name="add-disease"),
  path("disease/update/<int:pk>/", UpdateDisease.as_view(), name="update-disease"),
  path("disease/detail/<int:pk>/", DetailDisease.as_view(), name="detail-disease"),
  path("disease/view/", ViewDisease.as_view(), name="view-disease"),
  path("disease/delete/<int:pk>/", DeleteDisease.as_view(), name="delete-disease"),
  path("treatment/create/", CreateTreatment.as_view(), name="add-treatment"),
  path("treatment/update/<int:pk>/", UpdateTreatment.as_view(), name="update-treatment"),
  path("treatment/detail/<int:pk>/", DetailTreatment.as_view(), name="detail-treatment"),
  path("treatment/view/", ViewTreatment.as_view(), name="view-treatment"),
  path("treatment/delete/<int:pk>/", DeleteTreatment.as_view(), name="delete-treatment"),
  # path("filter/", FacilityFilterView.as_view())
  path("history/view", ViewHistoy.as_view(), name="history-view"),
  path("history/detail/<int:pk>", DetailHistory.as_view(), name="history-detail"),
]

patient_visit_patterns = [
  path("", VisitPatient.as_view(), name="patient_visit"),
  path("health/", PatientInfo.as_view(), name="health-info"),
  path("notes/view/", ViewTreatmentNotes.as_view(), name="treatment-notes"),
  path("notes/create/", AddTreatmentNotes.as_view(), name="add-notes"),
]

app_name = 'arike'
urlpatterns = [
  # path("facility/", SignInView.as_view(), name="login"),
  path("", HomeView.as_view(), name="homepage"),
  path("facility/create/", CreateFacility.as_view(), name='add-facility'),
  path("facility/update/<int:pk>/", UpdateFacility.as_view(), name='update-facility'),
  path("facility/detail/<int:pk>/", DetailFacility.as_view(), name='detail-facility'),
  path("facility/view/", ViewFacility.as_view(), name='view-facility'),
  path("facility/delete/<int:pk>/", DeleteFacility.as_view(), name='delete-facility'),
  path("patient/create/", CreatePatient.as_view(), name="add-patient"),
  path("patient/update/<int:pk>/", UpdatePatient.as_view(), name="update-patient"),
  path("patient/detail/<int:pk>/", DetailPatient.as_view(), name="detail-patient"),
  path("patient/view/", ViewPatient.as_view(), name="view-patient"),
  path("patient/delete/<int:pk>/", DeletePatient.as_view(), name="delete-patient"),
  path("patient/<int:pk1>/", include(patient_patterns)),
  path("visit/create/", CreateVisit.as_view(), name="add-visit"),
  # path("visit/update/<int:pk>/", UpdateVisit.as_view(), name="update-visit"),
  path("visit/detail/<int:pk>/", DetailVisit.as_view(), name="detail-visit"),
  path("visit/view/", ViewVisit.as_view(), name="view-visit"),
  path("visit/agenda/", Agenda.as_view(), name="agenda"),
  path("visit/delete/<int:pk>/", DeleteVisit.as_view(), name="delete-visit"),
  path("visit/<int:pk1>/", include(patient_visit_patterns)),
  # path("ajax/load_facilities/", load_facilities, name="ajax_facility_loader")
] + router.urls

arike/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from arike.users.views import DeleteUser, LoginView, CreateUser, UpdateUser, DetailUser, ViewUser, AssignFacilityUser, ChangeFacilityUser, ChangePassword

app_name = "user"
urlpatterns = [
  path("login/", LoginView.as_view(), name="login"),
  path("logout/", LogoutView.as_view(), name="logout"),
  # path("profile/", ProfileView.as_view(), name="profile"),
  path("create/", CreateUser.as_view(), name="add-user"),
  path("change/", ChangePassword.as_view(), name="change-password"),
  path("update/<int:pk>", UpdateUser.as_view(), name="update-user"),
  path("delete/<int:pk>", DeleteUser.as_view(), name="delete-user"),
  path("detail/<int:pk>", DetailUser.as_view(), name="detail-user"),
  path("assign/<int:pk>", AssignFacilityUser.as_view(), name="assign-facility"),
  path("change/<int:pk>", ChangeFacilityUser.as_view(), name="change-facility"),
  path("view/", ViewUser.as_view(), name="view-user")
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # path(
        # "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    # ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("user/", include("arike.users.urls", namespace="user")),
    path("", include("arike.facility.urls", namespace="arike"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    # path("api/", include("config.api_router")),
    # DRF auth token
    # path("auth-token/", obtain_auth_token),
    # path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    # path(
        # "api/docs/",
        # SpectacularSwaggerView.as_view(url_name="api-schema"),
        # name="api-docs",
    # ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

arike/facility/models/facility.py
from django.contrib.auth import get_user_model
from django.db import models
from arike.facility.models.mixins.permissions.facility import FacilityPermissionMixin
from arike.utils.models import BaseModel
from arike.utils.models import phone_number_regex
from arike.users.models import Ward
User = get_user_model()

FACILITY_TYPE = (
  (1, "PHC"),
  (2, "CHC"),
)

class Facility(BaseModel, FacilityPermissionMixin):
  ward = models.ForeignKey(Ward, on_delete=models.PROTECT)
  name = models.CharField(max_length=255)
  address = models.TextField()
  pincode = models.PositiveIntegerField()
  phone = models.CharField(max_length=14, validators=[phone_number_regex])
  kind = models.IntegerField(choices=FACILITY_TYPE, default=1)
  created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
  users = models.ManyToManyField(
    User, through="FacilityUser", related_name="facilities", through_fields=("facility", "user"),
  )

  def __str__(self):
    return f"{self.name}"

  def save(self, *args, **kwargs) -> None:
    is_create = self.pk is None
    super().save(*args, **kwargs)

    if is_create:
      FacilityUser.objects.create(facility=self, user=self.created_by, created_by=self.created_by)

class FacilityUser(models.Model):
  facility = models.ForeignKey(Facility, on_delete=models.CASCADE)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  created_by = models.ForeignKey(User, on_delete=models.PROTECT, related_name="created_users")

arike/facility/forms/facility.py
from django import forms
from django.forms import ModelForm
from arike.facility.models.facility import Facility

class FacilityForm(ModelForm):
  class Meta:
    model = Facility
    fields = ["name", "address", "ward", "phone", "pincode", "kind"]
    widgets = {
      "address": forms.Textarea(attrs={'rows': 5}),
    }

arike/facility/views/disease.py
import logging
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from arike.facility.models.patients import PatientDisease, Patient
from arike.facility.forms.patients import DiseaseForm
from arike.facility.views.family import AuthView

class CreateDisease(AuthView):
  template = "disease/create.html"
  form_class = DiseaseForm
  model = PatientDisease

  def get(self, request, pk1):
    try:
      form = self.form_class()
      return render(request, self.template, {"form": form})
    except Exception as e:
      logging.error(e)
      return HttpResponseRedirect("/500")

  def post(self, request, pk1):
    try:
      data = request.POST
      form = self.form_class(data)
      if form.is_valid():
        model_obj = form.save(commit=False)
        model_obj.patient_id = pk1
        model_obj.save()
        return HttpResponseRedirect(reverse("arike:view-disease", args=(pk1,)))
      return render(request, self.template, {"form": form})
    except Exception as e:
        logging.error(e)
        return HttpResponseRedirect("/500")

class UpdateDisease(AuthView):
  model = PatientDisease
  template = "disease/update.html"
  form_class = DiseaseForm

  def get(self, request, pk, pk1):
    try:
      model_obj = self.model.objects.get(id=pk, patient_id=pk1)
      form = self.form_class(instance=model_obj)
      return render(request, self.template, {"form": form})
    except Exception as e:
      logging.error(e)
      return HttpResponseRedirect("/500")

  def post(self, request, pk, pk1):
    try:
      model_obj = self.model.objects.get(id=pk, patient_id=pk1)
      data = request.POST
      form = self.form_class(data, instance=model_obj)
      if form.is_valid():
        model_obj = form.save(commit=False)
        model_obj.patient_id = pk1
        model_obj.save()
        return HttpResponseRedirect(reverse("arike:view-disease", args=(pk1,)))
      return render(request, self.template, {"form": form})
    except Exception as e:
      logging.error(e)
      return HttpResponseRedirect("/500")

class ViewDisease(AuthView):
  model = PatientDisease
  template = "disease/view.html"

  def get(self, request, pk1):
    try:
      current_user = request.user
      data = self.model.objects.filter(patient_id=pk1)
      dt = Patient.objects.get(id=pk1, created_by=current_user)
      return render(request, self.template, {"data": data, "dt": dt})
    except Exception as e:
      logging.error(e)
      return HttpResponseRedirect("/500")

class DetailDisease(AuthView):
  model = PatientDisease
  template = "disease/detail.html"
  form_class = DiseaseForm

  def get(self, request, pk, pk1):
    try:
      #current_user = request.user
      data = self.model.objects.get(id=pk, patient_id=pk1)
      return render(request, self.template, {"data": data, "pk1": pk1})
    except Exception as e:
      logging.error(e)
      return HttpResponseRedirect("/500")

class DeleteDisease(AuthView):
  model = PatientDisease
  template = "disease/delete.html"

  def get(self, request, pk, pk1):
    try:
      data = self.model.objects.get(id=pk, patient_id=pk1).disease
      return render(request, self.template, {"data": data})
    except Exception as e:
      logging.error(e)
      return HttpResponseRedirect("/500")

  def post(self, request, pk, pk1):
    try:
      res = request.POST.get("confirm_delete")
      if res == "yes":
        model_obj = self.model.objects.get(id=pk, patient_id=pk1)
        model_obj.delete()
      return HttpResponseRedirect(reverse("arike:view-disease", args=(pk1,)))
    except Exception as e:
      logging.error(e)
      return HttpResponseRedirect("/500")

arike/facility/views/family.py
import logging
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from arike.facility.models.patients import FamilyDetail, Patient
from arike.facility.forms.patients import FamilyForm

class AuthView(View):
  def dispatch(self, request, *args, **kwargs):
    if not request.user.is_authenticated:
      return HttpResponseRedirect('/user/login')
    if request.user.role > 15:
      return HttpResponseRedirect("/404")
    return super().dispatch(request, *args, **kwargs)

  def get_patient(self, pk):
    return Patient.objects.get(id=pk).full_name

class CreateFamily(AuthView):
  template = "family/create.html"
  form_class = FamilyForm

  def get(self, request, pk1):
    try:
      form = self.form_class()
      return render(request, self.template, {"form": form})
    except Exception as e:
      logging.error(e)
      return HttpResponseRedirect("/500")

  def post(self, request, pk1):
    try:
      data = request.POST
      form = self.form_class(data)
      if form.is_valid():
        model_obj = form.save(commit=False)
        model_obj.patient_id = pk1
        model_obj.save()
        return HttpResponseRedirect(reverse("arike:view-family", args=(pk1,)))
      return render(request, self.template, {"form": form})
    except Exception as e:
        logging.error(e)
        return HttpResponseRedirect("/500")

class UpdateFamily(AuthView):
  model = FamilyDetail
  template = "family/update.html"
  form_class = FamilyForm

  def get(self, request, pk, pk1):
    try:
      model_obj = self.model.objects.get(id=pk, patient_id=pk1)
      form = self.form_class(instance=model_obj)
      return render(request, self.template, {"form": form})
    except Exception as e:
      logging.error(e)
      return HttpResponseRedirect("/500")

  def post(self, request, pk, pk1):
    try:
      model_obj = self.model.objects.get(id=pk, patient_id=pk1)
      data = request.POST
      form = self.form_class(data, instance=model_obj)
      if form.is_valid():
        model_obj = form.save(commit=False)
        model_obj.patient_id = pk1
        model_obj.save()
        return HttpResponseRedirect(reverse("arike:view-family", args=(pk1,)))
      return render(request, self.template, {"form": form})
    except Exception as e:
      logging.error(e)
      return HttpResponseRedirect("/500")

class ViewFamily(AuthView):
  model = FamilyDetail
  template = "family/view.html"

  def get(self, request, pk1):
    try:
      current_user = request.user
      data = self.model.objects.filter(patient_id=pk1)
      dt = Patient.objects.get(id=pk1, created_by=current_user)
      return render(request, self.template, {"data": data, "dt": dt})
    except Exception as e:
      logging.error(e)
      return HttpResponseRedirect("/500")

class DetailFamily(AuthView):
  model = FamilyDetail
  template = "family/detail.html"

  def get(self, request, pk, pk1):
    try:
      data = self.model.objects.get(id=pk, patient_id=pk1)
      return render(request, self.template, {"data": data, "pk1": pk1})
    except Exception as e:
      logging.error(e)
      return HttpResponseRedirect("/500")

class DeleteFamily(AuthView):
  model = FamilyDetail
  template = "family/delete.html"

  def get(self, request, pk, pk1):
    try:
      data = self.model.objects.get(id=pk, patient_id=pk1).full_name
      return render(request, self.template, {"data": data})
    except Exception as e:
      logging.error(e)
      return HttpResponseRedirect("/500")

  def post(self, request, pk, pk1):
    try:
      res = request.POST.get("confirm_delete")
      if res == "yes":
        model_obj = self.model.objects.get(id=pk, patient_id=pk1)
        model_obj.delete()
      return HttpResponseRedirect(reverse("arike:view-family", args=(pk1,)))
    except Exception as e:
      logging.error(e)
      return HttpResponseRedirect("/500")

arike/facility/views/home.py
import logging
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

class HomeView(View):
  def get(self, request):
    try:
      user = self.request.user
      if user.is_active:
        role = user.role
        if role == 40:
          return redirect('arike:view-facility')
        else:
          return redirect('arike:view-patient')
      else:
        return HttpResponseRedirect('/user/login')
    except Exception as e:
      logging.error(e)
      return HttpResponseRedirect("/500")

arike/templates/facility/create.html
{% extends "base/form1.html" %}
{% block title %}
Create Facility
{% endblock title %}

arike/templates/facility/delete.html
{% extends "base/delete.html" %}
{% block title %}
Facility
{% endblock title %}

arike/templates/facility/detail.html
{% extends "base/detail.html" %}
{% load filters %}
{% block title %}
{{ data.name }}
{% endblock title %}
{% block buttons %}
<a href="{% url 'arike:delete-facility' data.id %}"
  class="w-1/2 px-6 py-3 text-lg text-white transition-all duration-150 ease-linear rounded-lg shadow outline-none bg-black hover:shadow-lg focus:outline-none">
  Delete
</a>
<a href="{% url 'arike:update-facility' data.id %}"
  class="w-1/2 px-6 py-3 text-lg text-white transition-all duration-150 ease-linear rounded-lg shadow outline-none bg-black hover:shadow-lg focus:outline-none">
  Update
</a>
{% endblock buttons %}
{% block extra %}
<fieldset disabled="disabled">
  <div id="div_id_name" class="mb-3">
    <label for="id_name" class="block text-gray-700 text-sm font-bold mb-2">Name</label>
    <input type="text" name="name" value="{{ data.name }}" maxlength="255"
      class="textinput focus:outline-none px-4 rounded-lg text-gray-700 w-full leading-normal appearance-none border-gray-300 py-2 block border bg-white">
  </div>
  <div id="div_id_address" class="mb-3">
    <label for="id_address" class="block text-gray-700 text-sm font-bold mb-2">Address</label>
    <textarea name="address" cols="40" rows="5"
      class="textarea resize-none focus:outline-none px-4 rounded-lg text-gray-700 w-full leading-normal appearance-none border-gray-300 py-2 block border bg-white">{{ data.address }} </textarea>
  </div>
  <div id="div_id_ward" class="mb-3">
    <label for="id_ward" class="block text-gray-700 text-sm font-bold mb-2">Ward</label>
    <div class="mb-3">
      <div class="relative">
        <span
          class="bg-white focus:outline-none border border-gray-300 rounded-lg py-2 px-4 block w-full appearance-none leading-normal text-gray-700"
          name="ward">{{ data.ward }}</span>
      </div>
    </div>
  </div>
  <div id="div_id_phone" class="mb-3">
    <label for="id_phone" class="block text-gray-700 text-sm font-bold mb-2">Phone</label>
    <input type="text" name="phone" value="{{ data.phone }}" maxlength="14"
      class="textinput focus:outline-none px-4 rounded-lg text-gray-700 w-full leading-normal appearance-none border-gray-300 py-2 block border bg-white">
  </div>
  <div id="div_id_pincode" class="mb-3">
    <label for="id_pincode" class="block text-gray-700 text-sm font-bold mb-2">Pincode</label>
    <input type="number" name="pincode" value="{{ data.pincode }}" min="0"
      class="numberinput focus:outline-none px-4 rounded-lg text-gray-700 w-full leading-normal appearance-none border-gray-300 py-2 block border bg-white">
  </div>
  <div id="div_id_kind" class="mb-3">
    <label for="id_kind" class="block text-gray-700 text-sm font-bold mb-2">Kind</label>
    <div class="mb-3">
      <div class="relative">
        <span
          class="bg-white focus:outline-none border border-gray-300 rounded-lg py-2 px-4 block w-full appearance-none leading-normal text-gray-700"
          name="kind">
          {{ data.kind|facility_type }}
        </span>
      </div>
    </div>
  </div>
</fieldset>
{% endblock extra %}

arike/templates/facility/update.html
{% extends "base/form1.html" %}
{% block title %}
Update Facility
{% endblock title %}

arike/templates/facility/view.html
{% extends "base/view2.html" %}
{% load filters %}
{% block title %}
Facility
{% endblock title %}
{% block button %}
<a href="{% url 'arike:add-facility' %}"
  class="w-1/4 text-center px-6 py-3 text-lg text-white transition-all duration-150 ease-linear rounded-lg shadow outline-none bg-black hover:shadow-lg focus:outline-none">
  Add
</a>
{% endblock button %}
{% block card %}
<a href="{% url 'arike:detail-facility' i.id %}">
  <div class="flex flex-row mb-4 w-full text-center">
    <span class="float-left truncate w-1/2 font-bold md:mt-4 text-xl text-gray-800 tracking-normal">
      {{ i.name }}
    </span>
    <span class="flaot-right bg-gray-200 text-md font-semibold rounded-full px-6 mt-4 ">
      {{ i.kind|facility_type }}</span>
  </div>
  </div>
  <p class="truncate text-md text-gray-700 px-2 mr-1"><strong>Address:</strong> {{ i.address}}</p>
  <p class="truncate text-md text-gray-700 px-2 mr-1"><strong>Pin Code:</strong> {{ i.pincode }}</p>
  <p class="truncate text-md text-gray-700 px-2 mr-1"><strong>Ward:</strong> {{ i.ward }}</p>
  <p class="truncate text-md text-gray-700 px-2 mr-1"><strong>Phone:</strong> {{ i.phone }}</p>
</a>
{% endblock card %}
{% block card_button %}
<a href="{% url 'arike:update-facility' i.id %}"
  class="bg-white border-2 border-black hover:bg-black text-black text-lg font-semibold hover:text-white rounded-full px-10 py-2">
  Edit </a>
<a href="{% url 'arike:delete-facility' i.id %}"
  class="bg-black hover:bg-white hover:border-2 hover:border-black text-lg font-semibold text-white hover:text-black rounded-full px-8 py-2">
  Delete </a>
</a>
{% endblock card_button %}
{% block href %}
{% endblock href %}