arike/facility/urls.py
from django.urls import include, path
from arike.facility.models.patients import TreatmentNotes
from arike.facility.view import CreateFacility, UpdateFacility, DetailFacility, ViewFacility, DeleteFacility
from arike.facility.views.patients import CreatePatient, UpdatePatient, ViewPatient, DetailPatient, DeletePatient, load_facilities
from arike.facility.views.family import CreateFamily, UpdateFamily, ViewFamily, DetailFamily, DeleteFamily
from arike.facility.views.disease import CreateDisease, UpdateDisease, ViewDisease, DetailDisease, DeleteDisease
from arike.facility.views.treatment import CreateTreatment, DeleteTreatment, DetailTreatment, UpdateTreatment, ViewTreatment
from arike.facility.views.home import HomeView
from arike.facility.views.visit import AddTreatmentNotes, Agenda, CreateVisit, DeleteVisit, DetailHistory, DetailVisit, PatientInfo, ViewHistoy, ViewTreatmentNotes, ViewVisit, VisitPatient
from arike.facility.viewset import FacilityViewSet
from rest_framework_nested import routers

router = routers.SimpleRouter()
router.register("api/facility", FacilityViewSet)

patient_patterns = [
  path("family/create/", CreateFamily.as_view(), name="add-family"),
  path("family/update/<int:pk>/", UpdateFamily.as_view(), name="update-family"),
  path("family/detail/<int:pk>/", DetailFamily.as_view(), name="detail-family"),
  path("family/view/", ViewFamily.as_view(), name="view-family"),
  path("family/delete/<int:pk>/", DeleteFamily.as_view(), name="delete-family"),
  path("disease/create/", CreateDisease.as_view(), name="add-disease"),
  path("disease/update/<int:pk>/", UpdateDisease.as_view(), name="update-disease"),
  path("disease/detail/<int:pk>/", DetailDisease.as_view(), name="detail-disease"),
  path("disease/view/", ViewDisease.as_view(), name="view-disease"),
  path("disease/delete/<int:pk>/", DeleteDisease.as_view(), name="delete-disease"),
  path("treatment/create/", CreateTreatment.as_view(), name="add-treatment"),
  path("treatment/update/<int:pk>/", UpdateTreatment.as_view(), name="update-treatment"),
  path("treatment/detail/<int:pk>/", DetailTreatment.as_view(), name="detail-treatment"),
  path("treatment/view/", ViewTreatment.as_view(), name="view-treatment"),
  path("treatment/delete/<int:pk>/", DeleteTreatment.as_view(), name="delete-treatment"),
  # path("filter/", FacilityFilterView.as_view())
  path("history/view", ViewHistoy.as_view(), name="history-view"),
  path("history/detail/<int:pk>", DetailHistory.as_view(), name="history-detail"),
]

patient_visit_patterns = [
  path("", VisitPatient.as_view(), name="patient_visit"),
  path("health/", PatientInfo.as_view(), name="health-info"),
  path("notes/view/", ViewTreatmentNotes.as_view(), name="treatment-notes"),
  path("notes/create/", AddTreatmentNotes.as_view(), name="add-notes"),
]

app_name = 'arike'
urlpatterns = [
  # path("facility/", SignInView.as_view(), name="login"),
  path("", HomeView.as_view(), name="homepage"),
  path("facility/create/", CreateFacility.as_view(), name='add-facility'),
  path("facility/update/<int:pk>/", UpdateFacility.as_view(), name='update-facility'),
  path("facility/detail/<int:pk>/", DetailFacility.as_view(), name='detail-facility'),
  path("facility/view/", ViewFacility.as_view(), name='view-facility'),
  path("facility/delete/<int:pk>/", DeleteFacility.as_view(), name='delete-facility'),
  path("patient/create/", CreatePatient.as_view(), name="add-patient"),
  path("patient/update/<int:pk>/", UpdatePatient.as_view(), name="update-patient"),
  path("patient/detail/<int:pk>/", DetailPatient.as_view(), name="detail-patient"),
  path("patient/view/", ViewPatient.as_view(), name="view-patient"),
  path("patient/delete/<int:pk>/", DeletePatient.as_view(), name="delete-patient"),
  path("patient/<int:pk1>/", include(patient_patterns)),
  path("visit/create/", CreateVisit.as_view(), name="add-visit"),
  # path("visit/update/<int:pk>/", UpdateVisit.as_view(), name="update-visit"),
  path("visit/detail/<int:pk>/", DetailVisit.as_view(), name="detail-visit"),
  path("visit/view/", ViewVisit.as_view(), name="view-visit"),
  path("visit/agenda/", Agenda.as_view(), name="agenda"),
  path("visit/delete/<int:pk>/", DeleteVisit.as_view(), name="delete-visit"),
  path("visit/<int:pk1>/", include(patient_visit_patterns)),
  # path("ajax/load_facilities/", load_facilities, name="ajax_facility_loader")
] + router.urls

arike/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from arike.users.views import DeleteUser, LoginView, CreateUser, UpdateUser, DetailUser, ViewUser, AssignFacilityUser, ChangeFacilityUser, ChangePassword

app_name = "user"
urlpatterns = [
  path("login/", LoginView.as_view(), name="login"),
  path("logout/", LogoutView.as_view(), name="logout"),
  # path("profile/", ProfileView.as_view(), name="profile"),
  path("create/", CreateUser.as_view(), name="add-user"),
  path("change/", ChangePassword.as_view(), name="change-password"),
  path("update/<int:pk>", UpdateUser.as_view(), name="update-user"),
  path("delete/<int:pk>", DeleteUser.as_view(), name="delete-user"),
  path("detail/<int:pk>", DetailUser.as_view(), name="detail-user"),
  path("assign/<int:pk>", AssignFacilityUser.as_view(), name="assign-facility"),
  path("change/<int:pk>", ChangeFacilityUser.as_view(), name="change-facility"),
  path("view/", ViewUser.as_view(), name="view-user")
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # path(
        # "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    # ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("user/", include("arike.users.urls", namespace="user")),
    path("", include("arike.facility.urls", namespace="arike"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    # path("api/", include("config.api_router")),
    # DRF auth token
    # path("auth-token/", obtain_auth_token),
    # path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    # path(
        # "api/docs/",
        # SpectacularSwaggerView.as_view(url_name="api-schema"),
        # name="api-docs",
    # ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

arike/facility/models/patients.py
import enum, itertools
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from arike.utils.models import BaseModel, phone_number_regex
from arike.facility.models.facility import Facility
from arike.users.models import Ward
from arike.facility.models.mixins.permissions.patient import PatientPermissionMixin

User = get_user_model()

GENDER_CHOICES = [(1, "Male"), (2, "Female"), (3, "Non-binary")]
class Patient(BaseModel, PatientPermissionMixin):
  full_name = models.CharField(max_length=255)
  date_of_birth = models.DateField(null=True)
  address = models.TextField(null=True, blank=False)
  landmark = models.TextField(null=True, blank=False)
  phone_number = models.CharField(max_length=14, validators=[phone_number_regex])
  gender = models.IntegerField(choices=GENDER_CHOICES, blank=False)
  emergency_phone_number = models.CharField(max_length=14, validators=[phone_number_regex])
  expired_time = models.TimeField(null=True, blank=True)
  ward = models.ForeignKey(Ward, on_delete=models.PROTECT, null=True, blank=True)
  facility = models.ForeignKey(Facility, on_delete=models.PROTECT, null=True, blank=True)
  created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="patient_created_by")

  def __str__(self):
    return f"{self.full_name}"

  def get_absolute_url(self):
    return reverse('arike:patient', kwargs={'pk': self.pk})

class RelationEnum(enum.IntEnum):
  FAMILY_MEMBER = 1
  FRIEND = 2
  RELATIVE = 3
  NEIGHBOR = 4
  TRAVEL_TOGETHER = 5
  WHILE_AT_HOSPITAL = 6
  WHILE_AT_SHOP = 7
  WHILE_AT_OFFICE_OR_ESTABLISHMENT = 8
  WORSHIP_PLACE = 9
  OTHERS = 10
RELATION_CHOICES = [(item.value, item.name) for item in RelationEnum]

class FamilyDetail(BaseModel):
  full_name = models.CharField(max_length=255)
  phone_number = models.CharField(max_length=14, validators=[phone_number_regex])
  date_of_birth = models.DateField(null=True)
  email = models.EmailField(null=True, blank=False)
  relation = models.IntegerField(choices=RELATION_CHOICES, default=1)
  address = models.TextField(null=True, blank=False)
  education = models.TextField(null=True, blank=False)
  occupation = models.TextField(null=True, blank=False)
  remarks = models.TextField(null=True, blank=False)
  is_primary = models.BooleanField(null=True)
  expired_time = models.TimeField(null=True, blank=True)
  patient = models.ForeignKey(Patient, on_delete=models.PROTECT, null=True, blank=True)

  def __str__(self):
    return f"{self.full_name}"


def reverse_choices(choices):
  output = []
  for choice in choices:
    output.append((choice[1], choice[0]))
  return output

ICDS_CHOICES = [
  ("DM", "D-32"), ("Hypertension", "HT-58"),
  ("IHD","IDH-21"), ("COPD", "DPOC-144"),
  ("Dementia", "DM-62"), ("CVA", "CAV-89"),
  ("Cancer", "C-98"), ("CKD", "DC-25")]

# class Disease(BaseModel):
#   DISEASE_CHOICES = reverse_choices(choices=ICDS_CHOICES)
#   icds_code = models.CharField(max_length=100, choices=ICDS_CHOICES)
#   disease = models.CharField(max_length=100, choices=DISEASE_CHOICES)

#   def __str__(self):
#     return f"{self.disease}"

class PatientDisease(BaseModel):
  # disease = models.ForeignKey(Disease, on_delete=models.PROTECT, null=True, blank=True)
  patient = models.ForeignKey(Patient, on_delete=models.PROTECT, null=True, blank=True)
  disease = models.CharField(max_length=100, choices=ICDS_CHOICES)
  note = models.TextField(null=True, blank=False)

class VisitSchedule(BaseModel):
  time = models.DateTimeField(null=True, blank=False)
  duration = models.CharField(null=True, blank=False, max_length=5)
  patient = models.ForeignKey(Patient, on_delete=models.PROTECT, null=True, blank=True)
  # user = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True)

PALLIATIVE_PHASE_CHOICES = [
  ("Stable", "Stable"), ("Unstable", "Unstable"),
  ("Deteriorating", "Deteriorating"), ("Dying", "Dying")
]

SYSTEMIC_EXAMINATION = [
  (1, "Cardiovascular"),
  (2, "Gastrointestinal"),
  (3, "Central Nervous System"),
  (4, "Respiratory"),
  (5, "Genital-urinary")
]

class VisitDetails(BaseModel):
  palliative_phase = models.CharField(max_length=50, choices=PALLIATIVE_PHASE_CHOICES, default=PALLIATIVE_PHASE_CHOICES[0][0])
  blood_pressure = models.CharField(max_length=50, null=True, blank=False)
  pulse = models.CharField(max_length=50, null=True, blank=False)
  general_random_blood_sugar = models.CharField(max_length=50, null=True, blank=False)
  personal_hygiene = models.TextField(null=True, blank=False)
  mouth_hygiene = models.TextField(null=True, blank=False)
  pubic_hygiene = models.TextField(null=True, blank=False)
  systemic_examination = models.IntegerField(choices=SYSTEMIC_EXAMINATION, default=0)
  patient_at_peace = models.BooleanField(null=True, blank=False)
  pain = models.BooleanField(null=True, blank=False)
  symptoms = models.TextField(null=True, blank=False)
  visit_schedule = models.ForeignKey(VisitSchedule, on_delete=models.PROTECT, null=True, blank=True)

CARE_CHOICES = {
  "General care": ["Mouth care", "Bath", "Nail cutting", "Shaving"],
  "Genito urinary care": [
    "Perennial care",
    "Condom catheterisation & training",
    "Nelcath catheterisation & training",
    "Foley's catheterisation",
    "Foley's catheter care",
    "Suprapubic catheterisation",
    "Suprapubic catheter care",
    "Bladder wash with normal saline",
    "Bladder wash with soda bicarbonate",
    "Urostomy care",
  ],
  "Gastro-intestinal care": [
    "Ryles tube insertion",
    "Ryles tube care",
    "Ryles tube feeding & training",
    "PEG care",
    "Per Rectal Enema",
    "High enema",
    "Bisacodyl Suppository",
    "Digital evacuation",
    "Colostomy care",
    "Colostomy irrigation care",
    "ileostomy care",
  ],
  "Wound care": [
    "Wound care training given to family",
    "Wound dressing",
    "Suture removal",
    "Vacuum dressing",
  ],
  "Respiratory care": [
    "Tracheostomy care",
    "Chest physiotherapy",
    "Inhaler training",
    "Oxygen concentrator - training",
    "Bi-PAP training",
    "Bandaging",
    "Upper limb lymphedema bandaging",
    "Lower limb lymphedema bandaging",
    "Upper limb lymphedema hosiery",
    "PVOD bandaging",
  ],
  "Invasive care": [
    "IV fluid infusion",
    "IV medicine bolus administration",
    "IV cannula care",
    "IV cannula insertion",
    "S/C cannula insertion",
    "S/C fluid infusion (subcutaneous)",
    "S/C medicine bolus administration",
    "S/C cannula care",
    "Ascites tapping",
    "Ascitic catheter care",
  ],
  "Physiotherapy": [
    "Passive Movement",
    "Active Movement",
    "Strengthening exercises",
    "NDT",
    "GAIT Training",
    "Modalities + text field",
    "Breathing exercises",
    "Balance & Coordination exercises",
    "Stretching",
    "Postural correction"]
}

def generate_choices(choices):
  output = []
  count = 1
  for choice in choices.keys():
    output.append((count, choice))
    count += 1
  return output

def sub_choice_generator(choices):
  output = []
  count = 1
  for key, value in (
      itertools.chain.from_iterable(
          [itertools.product((k, ), v) for k, v in choices.items()])):
              output.append((count, value))
              count += 1
  return output
CARE_TYPES = generate_choices(CARE_CHOICES)
CARE_SUB_TYPES = sub_choice_generator(CARE_CHOICES)
class Treatment(BaseModel):
  patient = models.ForeignKey(Patient, on_delete=models.PROTECT, null=True, blank=True)
  care_type = models.IntegerField(choices=CARE_TYPES, default=0)
  care_sub_type = models.IntegerField(choices=CARE_SUB_TYPES, blank=False)
  description = models.TextField(null=True, blank=False)

  def __str__(self):
    return f"{self.care_sub_type}"

class TreatmentNotes(BaseModel):
  notes = models.TextField(null=True, blank=False)
  description = models.TextField(null=True, blank=False)
  visit = models.ForeignKey(VisitSchedule, on_delete=models.PROTECT, null=True, blank=True)
  treatment = models.ForeignKey(Treatment, on_delete=models.PROTECT, null=True, blank=True)

arike/facility/forms/facility.py
from django import forms
from django.forms import ModelForm
from arike.facility.models.facility import Facility

class FacilityForm(ModelForm):
  class Meta:
    model = Facility
    fields = ["name", "address", "ward", "phone", "pincode", "kind"]
    widgets = {
      "address": forms.Textarea(attrs={'rows': 5}),
    }

arike/facility/views/home.py
import logging
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

class HomeView(View):
  def get(self, request):
    try:
      user = self.request.user
      if user.is_active:
        role = user.role
        if role == 40:
          return redirect('arike:view-facility')
        else:
          return redirect('arike:view-patient')
      else:
        return HttpResponseRedirect('/user/login')
    except Exception as e:
      logging.error(e)
      return HttpResponseRedirect("/500")

arike/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

arike/templates/visit_schedule/create.html
{% extends "base/form1.html" %}
{% block title %}
Add Treatment
{% endblock title %}

arike/templates/visit_schedule/detail.html
{% extends "base/detail.html" %}
{% load filters %}
{% block title %}
Visit Detail
{% endblock title %}
{% block extra %}
<fieldset disabled="disabled">
  <div class="flex flex-row">
    <div class="w-1/2">
      <div id="div_id_palliative_phase" class="mb-3">
        <label for="id_palliative_phase" class="block text-gray-700 text-sm font-bold mb-2">
          Palliative phase</label>
        <div class="mb-3">
          <div class="relative">
            <span
              class="bg-white focus:outline-none border border-gray-300 rounded-lg py-2 px-4 block w-full appearance-none leading-normal text-gray-700"
              name="palliative_phase">
              {{ data.palliative_phase }}
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="w-1/2 px-2">
      <div id="div_id_blood_pressure" class="mb-3">
        <label for="id_blood_pressure" class="block text-gray-700 text-sm font-bold mb-2">
          Blood pressure</label>
        <input type="text" name="blood_pressure" value="{{ data.blood_pressure }}" maxlength="50"
          class="textinput px-4 py-2 border-gray-300 text-gray-700 block focus:outline-none border w-full appearance-none bg-white leading-normal rounded-lg">
      </div>
    </div>
  </div>
  <div class="flex flex-row">
    <div class="w-1/3">
      <div id="div_id_pulse" class="mb-3">
        <label for="id_pulse" class="block text-gray-700 text-sm font-bold mb-2">
          Pulse</label>
        <input type="text" name="pulse" value="{{ data.pulse }}" maxlength="50"
          class="textinput px-4 py-2 border-gray-300 text-gray-700 block focus:outline-none border w-full appearance-none bg-white leading-normal rounded-lg">
      </div>
    </div>
    <div class="w-1/3 px-2">
      <div id="div_id_general_random_blood_sugar" class="mb-3">
        <label for="id_general_random_blood_sugar" class="block text-gray-700 text-sm font-bold mb-2">
          General random blood sugar</label>
        <input type="text" name="general_random_blood_sugar" value="{{ data.general_random_blood_sugar }}"
          maxlength="50"
          class="textinput px-4 py-2 border-gray-300 text-gray-700 block focus:outline-none border w-full appearance-none bg-white leading-normal rounded-lg">
      </div>
    </div>
    <div class="w-1/6 px-2">
      <div id="div_id_patient_at_peace" class="mb-3">
        <label for="id_patient_at_peace" class="block text-gray-700 text-sm font-bold mb-2">
          Patient at peace</label>
        <input type="checkbox" name="patient_at_peace" {% if data.patient_at_peace %} checked {% endif %}
          class="checkboxinput " id="id_patient_at_peace">
      </div>
    </div>
    <div class="w-1/6 px-2">
      <div id="div_id_pain" class="mb-3">
        <label for="id_pain" class="block text-gray-700 text-sm font-bold mb-2">
          Pain </label>
        <input type="checkbox" name="pain" {% if data.pain %} checked {%endif %} class="checkboxinput" id="id_pain">
      </div>
    </div>
  </div>
  <div class="flex flex-row">
    <div class="w-1/3">
      <div id="div_id_personal_hygiene" class="mb-3">
        <label for="id_personal_hygiene" class="block text-gray-700 text-sm font-bold mb-2">
          Personal hygiene</label>
        <textarea name="personal_hygiene" cols="40" rows="10"
          class="textarea px-4 py-2 border-gray-300 text-gray-700 block focus:outline-none border w-full appearance-none bg-white leading-normal rounded-lg">
        {{ data.personal_hygiene }} </textarea>
      </div>
    </div>
    <div class="w-1/3 px-2">
      <div id="div_id_mouth_hygiene" class="mb-3">
        <label for="id_mouth_hygiene" class="block text-gray-700 text-sm font-bold mb-2">
          Mouth hygiene</label>
        <textarea name="mouth_hygiene" cols="40" rows="10"
          class="textarea px-4 py-2 border-gray-300 text-gray-700 block focus:outline-none border w-full appearance-none bg-white leading-normal rounded-lg">{{ data.mouth_hygiene }}</textarea>
      </div>
    </div>
    <div class="w-1/3 px-2">
      <div id="div_id_pubic_hygiene" class="mb-3">
        <label for="id_pubic_hygiene" class="block text-gray-700 text-sm font-bold mb-2">
          Pubic hygiene</label>
        <textarea name="pubic_hygiene" cols="40" rows="10"
          class="textarea px-4 py-2 border-gray-300 text-gray-700 block focus:outline-none border w-full appearance-none bg-white leading-normal rounded-lg">{{ data.pubic_hygiene }}</textarea>
      </div>
    </div>
  </div>
  <div class="flex flex-row">
    <div class="w-1/3">
      <div id="div_id_systemic_examination" class="mb-3">
        <label for="id_systemic_examination" class="block text-gray-700 text-sm font-bold mb-2">
          Systemic examination</label>
        <div class="mb-3">
          <div class="relative">
            <span
              class="bg-white focus:outline-none border border-gray-300 rounded-lg py-2 px-4 block w-full appearance-none leading-normal text-gray-700"
              name="systemic_examination">
              {{ data.systemic_examination|get_systemic_examination }}
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="w-2/3 px-2">
      <div id="div_id_symptoms" class="mb-3">
        <label for="id_symptoms" class="block text-gray-700 text-sm font-bold mb-2">
          Symptoms</label>
        <textarea name="symptoms" cols="40" rows="10"
          class="textarea px-4 py-2 border-gray-300 text-gray-700 block focus:outline-none border w-full appearance-none bg-white leading-normal rounded-lg">{{ data.symptoms }}</textarea>
      </div>
    </div>
  </div>
</fieldset>
{% endblock extra %}

arike/templates/visit_schedule/update.html
{% extends "base/form1.html" %}
{% block title %}
Update Treatment
{% endblock title %}

arike/templates/visit_schedule/view.html
{% extends "base/view.html" %}
{% block title %}
Visit History
{% endblock title %}
{% block patient %}
<div class="ml-32 mt-20">
  <h1 class="font-bold text-3xl">{{ dt.full_name }}</h1>
  <span class="text-2xl">{{ dt.address }}</span>
</div>
{% endblock patient %}
{% block card %}
<!-- <div class="flex flex-row ml-10 px-10 my=3">
    <h4 class="truncate font-bold mr-10 md:mt-4 text-2xl text-gray-800 tracking-normal">
      {{ i.full_name }}
    </h4>
    <span class="text-white bg-gray-200 text-lg font-semibold rounded-full px-10 my-3 mt-5">{{ i.relation }}</span>
  </div> -->
</div>
<p class="truncate text-md text-gray-700 px-2 mr-1"><strong>Created at:</strong> {{ i.created_at }}</p>
<p class="truncate text-md text-gray-700 px-2 mr-1"><strong>Updated at:</strong> {{ i.updated_at }}</p>
{% endblock card %}
{% block card_button %}
<a href="{% url 'arike:history-detail' pk1=dt.pk pk=i.id %}"
  class="bg-white border-2 border-black hover:bg-black text-black text-lg font-semibold hover:text-white rounded-full px-10 py-2">
  Details </a>
{% endblock card_button %}

arike/templates/visit_schedule/visit_treatment.html
{% extends "base/view.html" %}
{% load filters %}
{% block content %}
<div class="flex flex-col -mt-10 justify-center">
  <div class="flex flex-row ml-60 mr-16 w-full space-x-14 w-1/2 justify-between align-middle">
    <h1 class="text-4xl font-bold">Treatment</h1>
  </div>

  <div class="ml-36 p-4 mt-10 w-1/2">
    <div class="bg-gray-50 md:bg-white md:shadow-xl rounded-lg mb-6">
      <div class="py-1">
        <div class="p-4">
          <div>
            <div class="flex flex-col ml-4 px-10 my-3">
              <h4 class="truncate font-bold mr-10 md:mt-4 text-2xl text-gray-800 tracking-normal">
                {{ info }}
              </h4>
            </div>
          </div>
          <div class="ml-10 mt-4">
            <p class="truncate text-lg text-gray-700 px-2 mr-1"><strong>Created:</strong> {{ dt.created_at }}</p>
            <p class="truncate text-lg text-gray-700 px-2 mr-1"><strong>Last updated:</strong> {{ dt.updated_at }}</p>
            <p class="truncate text-lg text-gray-700 px-2 mr-1"><strong>Description:</strong> {{ dt.description }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="flex flex-row ml-60 mt-10 mr-16 w-full space-x-14 w-1/2 justify-between align-middle">
    <h1 class="text-4xl font-bold">Notes</h1>
    <a href="{% url 'arike:add-notes' pk1=pk1 %}"
      class="w-1/4 text-center px-6 py-3 text-lg text-white transition-all duration-150 ease-linear rounded-lg shadow outline-none bg-black hover:shadow-lg focus:outline-none">
      Add
    </a>
  </div>
  <div class="flex flex-col gap-4 xl:mx-24 mt-10">
    {% for i in data %}
    <div class="p-4 w-3/4">
      <div class="bg-gray-50 md:bg-white md:shadow-xl rounded-lg mb-6">
        <div class="py-1">
          <div class="p-4">
            <div class="mt-4 flex flex-col flex-wrap">
              <div class="truncate text-md text-gray-700 px-2 mr-1"><strong>Created at:</strong>
                {{ i.created_at }}</div>
              <div class="truncate text-md text-gray-700 px-2 mr-1"><strong>Updated at:</strong>
                {{ i.updated_at }}</div>
              <div class="break-words w-full text-md text-gray-700 px-2 mr-1"><strong>Notes:</strong>
                {{ i.notes }}</div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}